### ISSUE TITLE
Remove unused parameters from datasources

### ISSUE THREAD

**Issue by damirabdul** [opendatadiscovery/odd-platform#1050]
Nowadays we have deprecated properties in datasources, which are no longer in use.

Need to:

1. Remove `connection_url` and `active` properties at all
2. Remove `pulling interval` from create/update form, but keep it in datasource overview form. In future we can receive this information from collector.

This affects both backend and frontend parts

## Useful information
Here are some useful links and information if you are new to this repository and OpenDataDiscovery system

### Documentation
We keep all documentation in our [GitBook](https://docs.opendatadiscovery.org/). It contains all kind of information such as
system overview and use cases (why are we doing this), architecture (how are we doing this), etc.
Please take a look at the `Developer Guides` section where we explain [how to contribute](https://docs.opendatadiscovery.org/developer-guides/how-to-contribute) and
[how to setup local environment](https://docs.opendatadiscovery.org/developer-guides/build-and-run/build-and-run-odd-platform)

### Contact us
If you're struggling with something, please feel free to ask us anything here in the GitHub issue ticket or via our [Slack community](https://go.opendatadiscovery.org/slack).

**Comment by Bhav00** [comment]
Are we talking about removing those two properties, `connection_url` and `active` from the file mentioned?
>odd-platform/docker/injector/datasources/datasources.json

May I know what other files potentially come under the radar that needs editing regarding this issue please?

**Comment by DementevNikita** [comment]
@Bhav00 it's actually more than that.

`connection_url` and `active` properties needs to be removed entirely out of the data source model, including database representation, simple pojos and dtos in the application, API endpoints, etc.

As for the `pulling interval` we'd like to keep this readonly in the platform. The only action that can potentially change this parameter in the database in future releases is when [collector is creating/updating data sources](https://github.com/opendatadiscovery/opendatadiscovery-specification/blob/dfa7973a98993fb10d0e7722e6c92c3b140ed025/specification/odd_api.yaml#L42). Since `pulling_interval` is not a part of `DataSource` model in the ODD Specification yet, this task's scope is to only 'hide' this property.

**Comment by Bhav00** [comment]
That ought to take a lot of reading of code, at least for me. I would like to read the code for a few days to see if I can help in doing something regarding this issue. Please feel free to assign it to someone else if he/she comes here to be assigned anyways.

**Comment by DementevNikita** [comment]
@Bhav00 sure thing, please take your time! Please take a look at the issue description, I've added useful links for you, there are documentation articles, developer guides, etc. Don't hesitate to ask us anything here in the thread or in Slack

**Comment by Bhav00** [comment]
Thank you very much
