### ISSUE TITLE
MetaData in the Data Entity not persisting in the ODD platform after few minutes(Approx 20 Mins)

### ISSUE THREAD

**Issue by mavenzer** [opendatadiscovery/odd-platform#1520]
So we added some metadata in the Data Entity and it's not persisting after few minutes i.e.(Approx 20 mins) in the web UI. We have added  2 metadata as string in our use case(50 chars long).

**ODD platform version 0.19.0**

**Comment by Vladysl** [comment]
Hi, could you please specify where you added this metadata information?
If you added metadata using UI, it should be there instantly.
Otherwise, it can be propagated via collectors using this field: https://github.com/opendatadiscovery/opendatadiscovery-specification/blob/eb83c5496398514ef548084b9ef76baa15f825d2/specification/entities.yaml#L18C14-L18C14.
Also, you can view the last update data.
<img width="1450" alt="image" src="https://github.com/opendatadiscovery/odd-platform/assets/45620393/1eef4817-7429-41fe-8ecf-9aa94fd0f7f8">

**Comment by clintjb** [comment]
The metadata was added over the UI and your correct its visible instantly - problem is if you go back to that dataset ~20mins later than the metadata tags are missing again...

**Comment by Vladysl** [comment]
The root cause of the problem is overwriting metadata by the collector.
Fix: All metadata that was created and added by the user using UI will not be overwritten by the collector.
We will fix it in next release.

**Comment by Vladysl** [comment]
implemented in https://github.com/opendatadiscovery/odd-platform/pull/1521
