### ISSUE TITLE
Linking Dictionary terms with Data-Entity leads to overflow.

### ISSUE THREAD

**Issue by mavenzer** [opendatadiscovery/odd-platform#1593]
We have deployed OpenDataDiscovery in K8s cluster. I'm not sure whether  the below issues   is bug or some weird thing going with our text formatting.   So when we  are linking dictionary terms with the data-entity, and going to the structure for each of the columns the text in the dictionary terms is overflowing.

ODD_Platform:  0.21.0 
ODD_Collector:  .32
Postgres DB  :  15.8 

As in the below image, the terms are overflowing and also the text within it. Would love to hear is this is a text formatting issue ? 
<img width="855" alt="test-2" src="https://github.com/opendatadiscovery/odd-platform/assets/24300927/84f3a8ca-17e9-4664-a16d-78bede3e0af9">

**Comment by AndreyNenashev** [comment]
@mavenzer Thanks for noticing. The term name is too long and we didn't consider that case, so it's a html makrup issue.
There are two options I see:

1. To truncate the term name if a name is too long.
2. Put description of a term under the name.

How is crucial for you to see the whole term name? It feels like option 2 is the most optimal solution here.

**Comment by mavenzer** [comment]
Hi @AndreyNenashev   thanks for the prompt response.  You are absolutely correct that option 2 looks more optimal to me as well. One more minor observation: the definition of dictionary terms when linked to data-entity, we are getting a scroll bar. But ideally we should go to a new line after a certain length  rather than using a scroll bar(much more visually IMO). It makes the terms definition more readable to the business users.  

<img width="594" alt="test-v3" src="https://github.com/opendatadiscovery/odd-platform/assets/24300927/513e6d91-8226-4e13-b8a2-a443fe45dc3a">

**Comment by AndreyNenashev** [comment]
It happens because of generated `markdown` html markup.
Github comments markdown example:

this is just a text - "some text"

this is a markdown:
```
very long line with multiple words. very long line with multiple words. very long line with multiple words. very long line with multiple words. very long line with multiple words. very long line with multiple words. very long line with multiple words. very long line with multiple words. very long line with multiple words.
```

It generates single inline block because in a markdown editor I didn't specify new lines explicitly inside the text. Unfortunately, we didn't consider that this block could contain a large amount of markdown text so it doesn't adjust well in these cases. So I will prepare some fix during this week. But long markdown blocks will have their scrolls anyway like in the example below.


<img width="594" alt="298678463-513e6d91-8226-4e13-b8a2-a443fe45dc3a" src="https://github.com/opendatadiscovery/odd-platform/assets/2155083/ea4a1d6d-53a5-4002-82bb-4d1c6a9b6fca">

**Comment by mavenzer** [comment]
Thanks a lot for the explanation the above fix is also more intuitive as well.
